### ISSUE TITLE
Move some types to a .Internal namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#292] opened 2015-04-25 08:59 UTC
now that we did the Http -> Http.Core swap we need to move some types into an internal namspace:

- BufferingHelper

**Comment by Tratcher** [comment] 2015-04-25 11:35
Dupe of https://github.com/aspnet/HttpAbstractions/issues/281, https://github.com/aspnet/HttpAbstractions/issues/271

**Closed by Tratcher** 2015-04-25 11:35 UTC
Labels: duplicate
