### ISSUE TITLE
Add `StatusDescription` to `HttpResponse` class

### ISSUE THREAD

**Issue by RexLKW** [aspnet/HttpAbstractions#794] opened 2017-03-19 00:26 UTC
In the old days, it is easy to modify the Http response status code and description, but now on asp.net core, we need to do something like:

`HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "It is my description";`

Consider adding `StatusDescription` back into `HttpResponse` class and its impl classes.

**Comment by davidfowl** [comment] 2017-03-19 00:30
It was left as a second class citizen because it's not a commonly used property.

/cc @Tratcher

**Comment by cesarbs** [comment] 2017-03-20 02:36
@RexLKW Could you elaborate on why you want this feature? Are you returning non-standard status codes? If not, why do you want to replace the standard reason phrases?

**Comment by JunTaoLuo** [comment] 2017-03-20 19:31
On a semi-related note, HTTP/2 will not have reason phrases.

**Comment by Tratcher** [comment] 2017-03-20 19:32
Duplicate of https://github.com/aspnet/HttpAbstractions/issues/395

**Closed** 2017-03-20 21:15 UTC
Labels: duplicate
