### ISSUE TITLE
OwinFeatureCollection: regression

### ISSUE THREAD

**Issue by borgdylan** [aspnet/HttpAbstractions#207] opened 2015-02-28 13:22 UTC
After some recent changes in the hosting pipeline, the OwinFeatureCollection is no longer handling requests (requests do not even get read by the request pipeline). If I populate a FeatureCollection using an OwinFeatureCollection, the requests gets handled by the request pipeline but the response never surfaces out to the client.

**Comment by borgdylan** [comment] 2015-02-28 19:13
After further investigation, the failures are happening as the setter is throwing a ```NotSupportedException```. Certain features like the one for service providers, send file and request cookies are being set triggering the exception. If one removes the throw statement, nothing is fixed and the same client side behaviour persists.

**Comment by Tratcher** [comment] 2015-03-01 00:34
Stack trace?

**Comment by borgdylan** [comment] 2015-03-01 06:31
The method in question is the indexer's setter. Will add a stack trace later.

**Comment by davidfowl** [comment] 2015-03-01 06:37
@borgdylan I'm interested in what changed that started to cause these problems.

**Comment by Tratcher** [comment] 2015-03-01 06:57
https://github.com/aspnet/Hosting/commit/435215b542586f2ab2f2a34df8e89b5bc7e52873

This I bet. The context factory assumed the incoming feature collection was read-only, so it wrapped it in mutable  collection. That wrapper was dropped in the last change, so it sounds like you're getting a notsupportedexception trying to call Set on a read-only feature collection.

Sent from my Windows Phone
________________________________

**Comment by davidfowl** [comment] 2015-03-01 07:00
Ah, good catch.

**Comment by davidfowl** [comment] 2015-03-01 08:21
@Praburaj Can you look at this? It's a regression caused by the code changes we made as a result of the API review. Add a test for it as well.

**Comment by borgdylan** [comment] 2015-03-01 08:27
@davidfowl  I agree with @Tratcher that this started to occur with IFeatureCollection being needed instead of an env object in the request handling delegate.

@Tratcher  Wrapping inside a mutable feature collection solves the exception issue as I have tried it. But the response body still does not get sent back to the client side.

**Comment by borgdylan** [comment] 2015-03-01 08:30
As an aside, Kestrel uses the mutable FeatureCollection directly. With that technique requests work OK. However I do get SignalR errors with respect to invalid delegate instructions.

**Comment by Praburaj** [comment] 2015-03-02 17:29
@borgdylan @Tratcher @davidfowl - I'll have a look at this today and add a test as well.

**Comment by Praburaj** [comment] 2015-03-02 18:18
@borgdylan what's the best way to reproduce this issue?

**Comment by Praburaj** [comment] 2015-03-02 18:18
I tried running a couple of `OWIN` based entropy samples and they seem to run fine.

**Comment by borgdylan** [comment] 2015-03-02 18:57
i have an updates server factory for nowin. Ill put it on github and you can try with it. It is what I am using.

**Comment by borgdylan** [comment] 2015-03-02 19:03
https://github.com/borgdylan/nowinfactory

**Comment by Praburaj** [comment] 2015-03-02 22:49
@borgdylan these changes already look to be in https://github.com/aspnet/Entropy/tree/dev/samples/Owin.Nowin.HelloWorld sample. This app seems to run fine. Does it require more than this to reproduce this issue?

**Comment by borgdylan** [comment] 2015-03-03 07:55
My code is similar but has a logger for exceptions. With that the code will fail but the exception will be silently hidden.

Regards,
              Dylan Borg B. Sc. (Hons) ICT (Melit.)
              borgdylan@hotmail.com
              borgdylang@gmail.com
              dylan.borg.11@um.edu.mt
              +00356 99214902


Date: Mon, 2 Mar 2015 14:49:08 -0800

**Comment by Praburaj** [comment] 2015-03-03 20:05
@borgdylan Thanks. Got it. 

Sent out a PR. https://github.com/aspnet/Hosting/pull/174

**Comment by Praburaj** [comment] 2015-03-04 01:01
merged the fix https://github.com/aspnet/Hosting/commit/fde3b0d2af5a7d8b595ef4f42e793c6263482caa

**Closed by Praburaj** 2015-03-04 01:01 UTC
Labels: 0 - Backlog, bug
